ekino_rendr.ekino_rendr_channel_type.*:
    type: "config_entity"
    label: 'Channel type config'
    mapping:
        id:
            type: "string"
            label: "ID"
        label:
            type: "label"
            label: "Label"
