version: "3.1"

services:
  rendr_drupal:
    build:
      context: .
      dockerfile: ./local/drupal/Dockerfile
    image: rendr_drupal:latest
    volumes:
      - ../src:/var/www/html
    environment:
      UNIX_UID: $UNIX_UID
      UNIX_GID: $UNIX_GID

    ports:
      - ${COMPOSE_BIND_IP:-0.0.0.0}:3000:3000
      - ${COMPOSE_BIND_IP:-0.0.0.0}:443:443
    depends_on:
      - postgres

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example
    restart: always
    ports:
      - ${COMPOSE_BIND_IP:-0.0.0.0}:5432:5432
