name: view-nextjs

type: "nodejs:12"

build:
  flavor: none

dependencies:
  nodejs:
    yarn: "*"

web:
  commands:
    start: yarn start -p ${PORT}

hooks:
  build: |
    yarn setup
    yarn next telemetry disable
    yarn next telemetry status
    rm dev.ts
    yarn build

disk: 512
